/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem.view;

import inventorysystem.model.*;
import inventorysystem.controller.*;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cy
 */
public class AccountView extends javax.swing.JFrame {
    private ArrayList<Account> accounts;
    private ArrayList<String> access_level = new ArrayList<>();
    private ArrayList<String> list_of_status = new ArrayList<>();
    private Account account;
    private Company company;
    
    public AccountView(Account account, Company company) {
        initComponents();
        this.account = account;
        this.company = company;
        
        this.loadAccessLevel();
        this.loadStatus();
        this.loadDatabase();
        this.fillAccountTable();
    }
    
    public JPanel getAccountView(){
        return jPanelAccountContainer;
    }
    
    private void loadDatabase(){
        AccountController ac = new AccountController();
        int selected_index = jComboBoxAccountStatusFilter.getSelectedIndex();
        String status_name = this.list_of_status.get(selected_index);
        
        if(status_name.equals("Inactive")){
            this.accounts = ac.getAccounts(this.company.getCompanyID(), "Inactive");
        }
        else if(status_name.equals("Active")){
            this.accounts = ac.getAccounts(this.company.getCompanyID(), "Active");
        }
        else{
            this.accounts = ac.getAccounts(this.company.getCompanyID());
        }
        
        this.fillAccountTable();
    }
    
    private void fillAccountTable(){
        DefaultTableModel model = (DefaultTableModel) jTableAccounts.getModel();
        
        model.setRowCount(0);
        
        int i = 0;
        for(Account accounT : this.accounts){
            int a_ID = accounT.getAccountID();
            String f_name = accounT.getFirstName();
            String l_name = accounT.getLastName();
            String username = accounT.getUsername();
            String email = accounT.getEmail();
            String access_lev = accounT.getAccessLevel();
            String status = accounT.getStatus();
            
            Object[] row_data = {a_ID, f_name, l_name, username, email, access_lev, status};
            model.insertRow(i, row_data);
            
            i++;
        }
    }
    
    private void loadAccessLevel(){
        jComboBoxAddAccessLevel.removeAllItems();
        jComboBoxEditAccessLevel.removeAllItems();
        
        String account_access_level = this.account.getAccessLevel();
        if(account_access_level.equals("Owner")){
            this.access_level.add("Staff");
            this.access_level.add("Admin");
            this.access_level.add("Owner");
        }
        else{
            this.access_level.add("Staff");
        }
        
        for(String access_lev : this.access_level){
            jComboBoxAddAccessLevel.addItem(access_lev);
            jComboBoxEditAccessLevel.addItem(access_lev);
        }
    }
    
    private void refresh(){
        this.loadDatabase();
        this.fillAccountTable();
        
        jPanelAccountContainer.removeAll();
        jPanelAccountContainer.add(jPanelAccount);
        jPanelAccountContainer.repaint();
        jPanelAccountContainer.revalidate();
    }
    
    public void loadStatus(){
        this.list_of_status.add("All");
        this.list_of_status.add("Active");
        this.list_of_status.add("Inactive");
        
        jComboBoxAccountStatusFilter.removeAllItems();
        
        int i = 0;
        for(String status : this.list_of_status){
            jComboBoxAccountStatusFilter.insertItemAt(status, i);
            i++;
        }
        
        jComboBoxAccountStatusFilter.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelModalAddAccount = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddFirstName = new javax.swing.JTextField();
        jTextFieldAddLastName = new javax.swing.JTextField();
        jTextFieldAddUsername = new javax.swing.JTextField();
        jTextFieldAddEmail = new javax.swing.JTextField();
        jComboBoxAddAccessLevel = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordFieldAddPassword = new javax.swing.JPasswordField();
        jPanelModalEditAccount = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldEditFirstName = new javax.swing.JTextField();
        jTextFieldEditLastName = new javax.swing.JTextField();
        jTextFieldEditEmail = new javax.swing.JTextField();
        jComboBoxEditAccessLevel = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelEditUsername = new javax.swing.JLabel();
        jPasswordFieldEditPassword = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabelEditAccountID = new javax.swing.JLabel();
        jPanelAccountContainer = new javax.swing.JPanel();
        jPanelAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAddAccount = new javax.swing.JButton();
        jButtonSetAccountInactive = new javax.swing.JButton();
        jButtonSetAccountActive = new javax.swing.JButton();
        jButtonEditAccount = new javax.swing.JButton();
        jButtonRefreshAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccounts = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxAccountStatusFilter = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelModalAddAccount.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Add Account");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last Name:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Username:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Access Level:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email:");

        jTextFieldAddUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddUsernameActionPerformed(evt);
            }
        });

        jTextFieldAddEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddEmailActionPerformed(evt);
            }
        });

        jComboBoxAddAccessLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelModalAddAccountLayout = new javax.swing.GroupLayout(jPanelModalAddAccount);
        jPanelModalAddAccount.setLayout(jPanelModalAddAccountLayout);
        jPanelModalAddAccountLayout.setHorizontalGroup(
            jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModalAddAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(223, 223, 223))
            .addGroup(jPanelModalAddAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModalAddAccountLayout.createSequentialGroup()
                        .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModalAddAccountLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAddUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModalAddAccountLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelModalAddAccountLayout.createSequentialGroup()
                                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelModalAddAccountLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jComboBoxAddAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldAddPassword))
                        .addGap(52, 52, 52))
                    .addGroup(jPanelModalAddAccountLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanelModalAddAccountLayout.setVerticalGroup(
            jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalAddAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAddUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordFieldAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxAddAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanelModalAddAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanelModalEditAccount.setBackground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Edit Account");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("First Name:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Last Name:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Username:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Password:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Access Level:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Email:");

        jTextFieldEditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditEmailActionPerformed(evt);
            }
        });

        jComboBoxEditAccessLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("Close");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Save");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabelEditUsername.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEditUsername.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEditUsername.setText("N/A");

        jPasswordFieldEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldEditPasswordActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Account ID:");

        jLabelEditAccountID.setBackground(new java.awt.Color(0, 0, 0));
        jLabelEditAccountID.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEditAccountID.setText("N/A");

        javax.swing.GroupLayout jPanelModalEditAccountLayout = new javax.swing.GroupLayout(jPanelModalEditAccount);
        jPanelModalEditAccount.setLayout(jPanelModalEditAccountLayout);
        jPanelModalEditAccountLayout.setHorizontalGroup(
            jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModalEditAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(223, 223, 223))
            .addGroup(jPanelModalEditAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModalEditAccountLayout.createSequentialGroup()
                        .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelModalEditAccountLayout.createSequentialGroup()
                                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEditUsername)
                                    .addGroup(jPanelModalEditAccountLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jComboBoxEditAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelModalEditAccountLayout.createSequentialGroup()
                                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEditAccountID)
                                    .addComponent(jTextFieldEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEditLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldEditPassword))
                        .addGap(52, 52, 52))
                    .addGroup(jPanelModalEditAccountLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        jPanelModalEditAccountLayout.setVerticalGroup(
            jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalEditAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelEditAccountID))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabelEditUsername)
                    .addComponent(jPasswordFieldEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxEditAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanelModalEditAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanelAccountContainer.setBackground(new java.awt.Color(0, 204, 204));

        jPanelAccount.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Accounts");

        jButtonAddAccount.setText("Add");
        jButtonAddAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddAccountMouseClicked(evt);
            }
        });

        jButtonSetAccountInactive.setText("Set as Inactive");
        jButtonSetAccountInactive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSetAccountInactiveMouseClicked(evt);
            }
        });

        jButtonSetAccountActive.setText("Set as Active");
        jButtonSetAccountActive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSetAccountActiveMouseClicked(evt);
            }
        });

        jButtonEditAccount.setText("Edit");
        jButtonEditAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditAccountMouseClicked(evt);
            }
        });

        jButtonRefreshAccount.setText("Refresh");
        jButtonRefreshAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRefreshAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddAccount)
                .addGap(18, 18, 18)
                .addComponent(jButtonSetAccountInactive)
                .addGap(18, 18, 18)
                .addComponent(jButtonSetAccountActive)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButtonRefreshAccount)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAccount)
                    .addComponent(jButtonSetAccountInactive)
                    .addComponent(jButtonSetAccountActive)
                    .addComponent(jButtonEditAccount)
                    .addComponent(jButtonRefreshAccount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "First Name", "Last Name", "Username", "Email", "Access Level", "Status", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAccounts);
        if (jTableAccounts.getColumnModel().getColumnCount() > 0) {
            jTableAccounts.getColumnModel().getColumn(7).setMaxWidth(15);
        }

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Status: ");

        jComboBoxAccountStatusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Filter");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccountLayout = new javax.swing.GroupLayout(jPanelAccount);
        jPanelAccount.setLayout(jPanelAccountLayout);
        jPanelAccountLayout.setHorizontalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelAccountLayout.createSequentialGroup()
                        .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelAccountLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxAccountStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAccountLayout.setVerticalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxAccountStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAccountContainerLayout = new javax.swing.GroupLayout(jPanelAccountContainer);
        jPanelAccountContainer.setLayout(jPanelAccountContainerLayout);
        jPanelAccountContainerLayout.setHorizontalGroup(
            jPanelAccountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(jPanelAccountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAccountContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelAccountContainerLayout.setVerticalGroup(
            jPanelAccountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(jPanelAccountContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAccountContainerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelModalAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAccountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jPanelModalEditAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelModalAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAccountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jPanelModalEditAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAddUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddUsernameActionPerformed

    private void jTextFieldAddEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddEmailActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jPanelAccountContainer.removeAll();
        jPanelAccountContainer.add(jPanelAccount);
        jPanelAccountContainer.repaint();
        jPanelAccountContainer.revalidate();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonAddAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddAccountMouseClicked
        jPanelAccountContainer.removeAll();
        jPanelAccountContainer.add(jPanelModalAddAccount);
        jPanelAccountContainer.repaint();
        jPanelAccountContainer.revalidate();
    }//GEN-LAST:event_jButtonAddAccountMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int selected_index = jComboBoxAddAccessLevel.getSelectedIndex();
        String access_lev = this.access_level.get(selected_index);
        String f_name = jTextFieldAddFirstName.getText();
        String l_name = jTextFieldAddLastName.getText();
        String username = jTextFieldAddUsername.getText();
        String email = jTextFieldAddEmail.getText();
        String password = jPasswordFieldAddPassword.getText();
        
        if(username.equals("")){
            System.out.println("Username must not be empty");
            return;
        }
        
        if(email.equals("")){
            System.out.println("Email must not be empty");
            return;
        }
        
        if(password.equals("")){
            System.out.println("Password must not be empty");
            return;
        }
        
        AccountController ac = new AccountController();
        
        boolean is_username_found = ac.findUsername(username);
        if(is_username_found){
            System.out.println("Please enter different username");
            return;
        }
        
        boolean is_email_found = ac.findEmail(email);
        if(is_email_found){
            System.out.println("Please enter different email");
            return;
        }
        
        ac.createAccount(this.company.getCompanyID(), f_name, l_name, username, password, access_lev, email);
        
        this.loadDatabase();
        this.fillAccountTable();
        
        jPanelAccountContainer.removeAll();
        jPanelAccountContainer.add(jPanelAccount);
        jPanelAccountContainer.repaint();
        jPanelAccountContainer.revalidate();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButtonSetAccountInactiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSetAccountInactiveMouseClicked
        AccountController ac = new AccountController();
        DefaultTableModel model = (DefaultTableModel) jTableAccounts.getModel();
        
        String account_access = this.account.getAccessLevel();
        
        int table_size = model.getRowCount();
        
        for(int i = 0; i < table_size; i++){
            Boolean is_checked = (Boolean) model.getValueAt(i, 7);
            if(is_checked != null && is_checked){
                String access_lev = (String) model.getValueAt(i, 5);
                
                if(account_access.equals("Admin") && access_lev.equals("Admin")){
                    continue;
                }
                if(access_lev.equals("Owner")){
                    continue;
                }
                int account_ID = (int) model.getValueAt(i, 0);
                ac.setAccountStatus(account_ID, "Inactive");
            }
        }
        this.refresh();
    }//GEN-LAST:event_jButtonSetAccountInactiveMouseClicked

    private void jButtonRefreshAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRefreshAccountMouseClicked
        this.refresh();
    }//GEN-LAST:event_jButtonRefreshAccountMouseClicked

    private void jButtonSetAccountActiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSetAccountActiveMouseClicked
        AccountController ac = new AccountController();
        DefaultTableModel model = (DefaultTableModel) jTableAccounts.getModel();
        
        int table_size = model.getRowCount();
        
        for(int i = 0; i < table_size; i++){
            Boolean is_checked = (Boolean) model.getValueAt(i, 7);
            if(is_checked != null && is_checked){
                int account_ID = (int) model.getValueAt(i, 0);
                ac.setAccountStatus(account_ID, "Active");
            }
        }
        this.refresh();
    }//GEN-LAST:event_jButtonSetAccountActiveMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.loadDatabase();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextFieldEditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditEmailActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.refresh();
        jPanelAccountContainer.removeAll();
        jPanelAccountContainer.add(jPanelAccount);
        jPanelAccountContainer.repaint();
        jPanelAccountContainer.revalidate();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        AccountController ac = new AccountController();
        int selected_index = jComboBoxEditAccessLevel.getSelectedIndex();
        
        String access_lev = this.access_level.get(selected_index);
        String f_name = jTextFieldEditFirstName.getText();
        String l_name = jTextFieldEditLastName.getText();
        int account_ID = Integer.parseInt(jLabelEditAccountID.getText());
        String email = jTextFieldEditEmail.getText();
        String password = jPasswordFieldEditPassword.getText();
        
        if(password.equals("")){
            ac.editAccount(account_ID, f_name, l_name, email, access_lev);
        }
        else{
            ac.editAccount(account_ID, f_name, l_name, password, email, access_lev);
        }
        
        this.refresh();
        
        jPanelAccountContainer.removeAll();
        jPanelAccountContainer.add(jPanelAccount);
        jPanelAccountContainer.repaint();
        jPanelAccountContainer.revalidate();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jPasswordFieldEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldEditPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldEditPasswordActionPerformed

    private void jButtonEditAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditAccountMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableAccounts.getModel();
        AccountController ac = new AccountController();
        
        int current_account_ID = this.account.getAccountID();
        
        int table_size = model.getRowCount();
        for(int i = 0; i < table_size; i++){
            Boolean is_checked = (Boolean) model.getValueAt(i, 7);
            if(is_checked != null && is_checked){
                int account_ID = this.accounts.get(i).getAccountID();
                if(current_account_ID == account_ID){
                    continue;
                }
                
                String f_name = this.accounts.get(i).getFirstName();
                String l_name = this.accounts.get(i).getLastName();
                String username = this.accounts.get(i).getUsername();
                String password = this.accounts.get(i).getPassword();
                String email = this.accounts.get(i).getEmail();
                String access_lev = this.accounts.get(i).getAccessLevel();
                int selected_index = 0;
                
                int j = 0;
                for (String str_access_lev : this.access_level) {
                    if(str_access_lev.equals(access_lev)){
                        selected_index = j;
                    }
                    j++;
                }
                
                
                if(access_lev.equals("Owner")){
                    continue;
                }
                
                jPanelAccountContainer.removeAll();
                jPanelAccountContainer.add(jPanelModalEditAccount);
                jPanelAccountContainer.repaint();
                jPanelAccountContainer.revalidate();
                
                jTextFieldEditFirstName.setText(f_name);
                jTextFieldEditLastName.setText(l_name);
                jLabelEditUsername.setText(username);
                jLabelEditAccountID.setText(Integer.toString(account_ID));
                jTextFieldEditEmail.setText(email);
//                jPasswordFieldEditPassword.setText(password);
                jComboBoxEditAccessLevel.setSelectedIndex(selected_index);
            }
        }
    }//GEN-LAST:event_jButtonEditAccountMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AccountView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAddAccount;
    private javax.swing.JButton jButtonEditAccount;
    private javax.swing.JButton jButtonRefreshAccount;
    private javax.swing.JButton jButtonSetAccountActive;
    private javax.swing.JButton jButtonSetAccountInactive;
    private javax.swing.JComboBox<String> jComboBoxAccountStatusFilter;
    private javax.swing.JComboBox<String> jComboBoxAddAccessLevel;
    private javax.swing.JComboBox<String> jComboBoxEditAccessLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEditAccountID;
    private javax.swing.JLabel jLabelEditUsername;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelAccountContainer;
    private javax.swing.JPanel jPanelModalAddAccount;
    private javax.swing.JPanel jPanelModalEditAccount;
    private javax.swing.JPasswordField jPasswordFieldAddPassword;
    private javax.swing.JPasswordField jPasswordFieldEditPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccounts;
    private javax.swing.JTextField jTextFieldAddEmail;
    private javax.swing.JTextField jTextFieldAddFirstName;
    private javax.swing.JTextField jTextFieldAddLastName;
    private javax.swing.JTextField jTextFieldAddUsername;
    private javax.swing.JTextField jTextFieldEditEmail;
    private javax.swing.JTextField jTextFieldEditFirstName;
    private javax.swing.JTextField jTextFieldEditLastName;
    // End of variables declaration//GEN-END:variables
}
