/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysystem.view;

import inventorysystem.model.*;
import inventorysystem.controller.*;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cy
 */
public class ProductView extends javax.swing.JFrame {
    private ArrayList<Inventory> active_inventories;
    private Account account;
    private Company company;

    /**
     * Creates new form ProductView
     */
    public ProductView(Account account, Company company) {
        initComponents();
        
        this.account = account;
        this.company = company;
        this.loadActiveInventory();
    }
    
    public JPanel getProductView(){
        return jPanelProductContainer;
    }
    
    public void loadActiveInventory(){
        InventoryController ic = new InventoryController();
        this.active_inventories = ic.getActiveInventories(this.company.getCompanyID());
        
        jComboBoxProductsInventoryName.removeAllItems();
        jComboBoxEditInventoryName.removeAllItems();
        jComboBoxAddProductInventory.removeAllItems();
        
        int i = 0;
        for(Inventory inventory : this.active_inventories){
            jComboBoxProductsInventoryName.insertItemAt(inventory.getInventoryName(), i);
            jComboBoxEditInventoryName.insertItemAt(inventory.getInventoryName(), i);
            jComboBoxAddProductInventory.insertItemAt(inventory.getInventoryName(), i);
            i++;
        }
        
        if(this.active_inventories != null && !this.active_inventories.isEmpty()){
            jComboBoxProductsInventoryName.setSelectedIndex(0);
            jComboBoxEditInventoryName.setSelectedIndex(0);
            jComboBoxAddProductInventory.setSelectedIndex(0);
        }
        
        
        
        this.refresh();
    }
    
    public void refresh(){
        jPanelProductContainer.removeAll();
        jPanelProductContainer.add(jPanelProducts);
        jPanelProductContainer.repaint();
        jPanelProductContainer.revalidate();
        
        int selected_index = jComboBoxProductsInventoryName.getSelectedIndex();
        if(selected_index != -1){
            int inventory_ID = this.active_inventories.get(selected_index).getInventoryID();
            ProductController pc = new ProductController(inventory_ID);
            ArrayList<Product> products = pc.getProducts();
            DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();

            model.setRowCount(0);

            for(Product product : products){
                Object[] row_data = {product.getProductID(), product.getProductName(), product.getProductDescription(), product.getQuantity(), product.getStatus()};
                model.addRow(row_data);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelModalAddProduct = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddProductName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddProductDescription = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAddProductQuantity = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBoxAddProductInventory = new javax.swing.JComboBox<>();
        jPanelModalEditProduct = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelEditProductID = new javax.swing.JLabel();
        jTextFieldEditProductName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEditProductDescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxEditInventoryName = new javax.swing.JComboBox<>();
        jPanelProductContainer = new javax.swing.JPanel();
        jPanelProducts = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAddProduct = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxProductsInventoryName = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jButtonFilterProducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelModalAddProduct.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Product");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inventory Name:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Product Name:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Product Description:");

        jTextFieldAddProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddProductNameActionPerformed(evt);
            }
        });

        jTextAreaAddProductDescription.setColumns(20);
        jTextAreaAddProductDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddProductDescription);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity");

        jButton5.setText("Add");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton7.setText("Close");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jComboBoxAddProductInventory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAddProductInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAddProductInventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModalAddProductLayout = new javax.swing.GroupLayout(jPanelModalAddProduct);
        jPanelModalAddProduct.setLayout(jPanelModalAddProductLayout);
        jPanelModalAddProductLayout.setHorizontalGroup(
            jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalAddProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModalAddProductLayout.createSequentialGroup()
                        .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanelModalAddProductLayout.createSequentialGroup()
                                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelModalAddProductLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldAddProductQuantity)
                                            .addComponent(jScrollPane1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModalAddProductLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxAddProductInventory, 0, 234, Short.MAX_VALUE)
                                            .addComponent(jTextFieldAddProductName)))))
                            .addComponent(jLabel11))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModalAddProductLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModalAddProductLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        jPanelModalAddProductLayout.setVerticalGroup(
            jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalAddProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxAddProductInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAddProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldAddProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addGap(7, 7, 7))
        );

        jPanelModalEditProduct.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edit Product");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product ID: ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inventory Name:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Product Name:");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Product Description");

        jLabelEditProductID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditProductID.setText("N/A");

        jTextFieldEditProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditProductNameActionPerformed(evt);
            }
        });

        jTextAreaEditProductDescription.setColumns(20);
        jTextAreaEditProductDescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaEditProductDescription);

        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jComboBoxEditInventoryName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelModalEditProductLayout = new javax.swing.GroupLayout(jPanelModalEditProduct);
        jPanelModalEditProduct.setLayout(jPanelModalEditProductLayout);
        jPanelModalEditProductLayout.setHorizontalGroup(
            jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalEditProductLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(170, 170, 170))
            .addGroup(jPanelModalEditProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModalEditProductLayout.createSequentialGroup()
                        .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEditProductID)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxEditInventoryName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEditProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelModalEditProductLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanelModalEditProductLayout.setVerticalGroup(
            jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalEditProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelEditProductID))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxEditInventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldEditProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelModalEditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanelProductContainer.setBackground(new java.awt.Color(0, 204, 204));

        jPanelProducts.setBackground(new java.awt.Color(0, 204, 204));

        jButtonAddProduct.setText("Add");
        jButtonAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddProductMouseClicked(evt);
            }
        });
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButton6.setText("Set as Inactive");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton13.setText("Set as Active");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton14.setText("Edit");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jButton15.setText("Refresh");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddProduct)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddProduct)
                    .addComponent(jButton6)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Products");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Inventory Name:");

        jComboBoxProductsInventoryName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Description", "Quantity", "Status", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableProducts);

        jButtonFilterProducts.setText("Filter");
        jButtonFilterProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFilterProductsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductsLayout = new javax.swing.GroupLayout(jPanelProducts);
        jPanelProducts.setLayout(jPanelProductsLayout);
        jPanelProductsLayout.setHorizontalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanelProductsLayout.createSequentialGroup()
                        .addGroup(jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanelProductsLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxProductsInventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonFilterProducts)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelProductsLayout.setVerticalGroup(
            jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductsLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanelProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jComboBoxProductsInventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilterProducts))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelProductContainerLayout = new javax.swing.GroupLayout(jPanelProductContainer);
        jPanelProductContainer.setLayout(jPanelProductContainerLayout);
        jPanelProductContainerLayout.setHorizontalGroup(
            jPanelProductContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanelProductContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelProductContainerLayout.setVerticalGroup(
            jPanelProductContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanelProductContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelProductContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelProductContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jPanelModalAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jPanelModalEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelProductContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jPanelModalAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jPanelModalEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddProductMouseClicked
        jPanelProductContainer.removeAll();
        jPanelProductContainer.add(jPanelModalAddProduct);
        jPanelProductContainer.repaint();
        jPanelProductContainer.revalidate();

//        InventoryController ic = new InventoryController(this.company.getCompanyID());

//        int i = 0;
//        for(Inventory inventory : this.active_inventories){
//            jComboBoxAddProductInventory.insertItemAt(inventory.getInventoryName(), i);
//            i++;
//        }
    }//GEN-LAST:event_jButtonAddProductMouseClicked

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        ProductController pc = new ProductController();
        DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();
        int table_size = model.getRowCount();

        for(int i = 0; i < table_size; i++){
            Boolean is_check = (Boolean) model.getValueAt(i, 5);
            if(is_check != null && is_check){
                int product_ID = (int) model.getValueAt(i, 0);
                pc.updateProduct(product_ID, "Inactive");
            }
        }
        this.refresh();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        ProductController pc = new ProductController();
        DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();
        int table_size = model.getRowCount();

        for(int i = 0; i < table_size; i++){
            Boolean is_check = (Boolean) model.getValueAt(i, 5);
            if(is_check != null && is_check){
                int product_ID = (int) model.getValueAt(i, 0);
                pc.updateProduct(product_ID, "Active");
            }
        }
        this.refresh();
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        this.refresh();
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButtonFilterProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFilterProductsMouseClicked
        int selected_index = jComboBoxProductsInventoryName.getSelectedIndex();
        int inventory_ID = this.active_inventories.get(selected_index).getInventoryID();
        if(inventory_ID != -1){

            ProductController pc = new ProductController(inventory_ID);
            ArrayList<Product> products = pc.getProducts();
            DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();
            model.setRowCount(0);

            for(Product product : products){

                int product_ID = product.getProductID();
                String product_name = product.getProductName();
                String product_description = product.getProductDescription();
                int quantity = product.getQuantity();
                String status = product.getStatus();

                Object[] rowData = {product_ID, product_name, product_description, quantity, status, false, false};

                model.addRow(rowData);
            }
        }
    }//GEN-LAST:event_jButtonFilterProductsMouseClicked

    private void jTextFieldAddProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddProductNameActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        int selected_index = jComboBoxAddProductInventory.getSelectedIndex();
        int inventory_ID = this.active_inventories.get(selected_index).getInventoryID();
        ProductController pc = new ProductController();
        String product_name = jTextFieldAddProductName.getText();
        String product_description = jTextAreaAddProductDescription.getText();
        int quantity = Integer.parseInt(jTextFieldAddProductQuantity.getText());

        pc.createProduct(inventory_ID, product_name, product_description, quantity);

        jPanelProductContainer.removeAll();
        jPanelProductContainer.add(jPanelProducts);
        jPanelProductContainer.repaint();
        jPanelProductContainer.revalidate();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        jPanelProductContainer.removeAll();
        jPanelProductContainer.add(jPanelProducts);
        jPanelProductContainer.repaint();
        jPanelProductContainer.revalidate();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jComboBoxAddProductInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAddProductInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAddProductInventoryActionPerformed

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableProducts.getModel();
        
        int table_size = model.getRowCount();
        
        for(int i = 0; i < table_size; i++){
            Boolean is_checked = (Boolean) model.getValueAt(i, 5);
            if(is_checked != null && is_checked){
                jPanelProductContainer.removeAll();
                jPanelProductContainer.add(jPanelModalEditProduct);
                jPanelProductContainer.repaint();
                jPanelProductContainer.revalidate();
                
                int product_ID = (int) model.getValueAt(i, 0);
                int selected_index = jComboBoxProductsInventoryName.getSelectedIndex();
                String product_name = (String) model.getValueAt(i, 1);
                String product_description = (String) model.getValueAt(i, 2);
                
                jLabelEditProductID.setText(Integer.toString(product_ID));
                jComboBoxEditInventoryName.setSelectedIndex(selected_index);
                jTextFieldEditProductName.setText(product_name);
                jTextAreaEditProductDescription.setText(product_description);
            }
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jTextFieldEditProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditProductNameActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.refresh();
        
        jPanelProductContainer.removeAll();
        jPanelProductContainer.add(jPanelProducts);
        jPanelProductContainer.repaint();
        jPanelProductContainer.revalidate();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ProductController pc = new ProductController();
        int selected_index = jComboBoxEditInventoryName.getSelectedIndex();
        
        int inventory_ID = this.active_inventories.get(selected_index).getInventoryID();
        int product_ID = Integer.parseInt(jLabelEditProductID.getText());
        String product_name = jTextFieldEditProductName.getText();
        String description = jTextAreaEditProductDescription.getText();
        
        pc.updateProduct(product_ID, inventory_ID, product_name, description);
        
        this.refresh();
        
        jPanelProductContainer.removeAll();
        jPanelProductContainer.add(jPanelProducts);
        jPanelProductContainer.repaint();
        jPanelProductContainer.revalidate();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProductView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonFilterProducts;
    private javax.swing.JComboBox<String> jComboBoxAddProductInventory;
    private javax.swing.JComboBox<String> jComboBoxEditInventoryName;
    private javax.swing.JComboBox<String> jComboBoxProductsInventoryName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEditProductID;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelModalAddProduct;
    private javax.swing.JPanel jPanelModalEditProduct;
    private javax.swing.JPanel jPanelProductContainer;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JTextArea jTextAreaAddProductDescription;
    private javax.swing.JTextArea jTextAreaEditProductDescription;
    private javax.swing.JTextField jTextFieldAddProductName;
    private javax.swing.JTextField jTextFieldAddProductQuantity;
    private javax.swing.JTextField jTextFieldEditProductName;
    // End of variables declaration//GEN-END:variables
}
